-- BOARD_NOTIFICATION1 테이블 생성 쿼리
-- 알림 기능을 위한 테이블

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD_NOTIFICATION1
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 알림 테이블 생성
CREATE TABLE BOARD_NOTIFICATION1 (
    NOTIFICATION_SEQ NUMBER PRIMARY KEY,              -- 알림 번호 (PK, 시퀀스)
    MEMBER_ID VARCHAR2(50) NOT NULL,                  -- 회원 ID (FK -> MEMBER1.ID)
    NOTIFICATION_TYPE VARCHAR2(20) NOT NULL,          -- 알림 타입 (게시글댓글/게시글좋아요/댓글댓글 등)
    RELATED_POST_SEQ NUMBER,                          -- 관련 게시글 번호 (FK -> BOARD_POST1.POST_SEQ)
    RELATED_COMMENT_SEQ NUMBER,                       -- 관련 댓글 번호 (FK -> BOARD_COMMENT1.COMMENT_SEQ)
    NOTIFICATION_CONTENT VARCHAR2(500),               -- 알림 내용
    IS_READ VARCHAR2(1) DEFAULT 'N',                  -- 읽음 여부 (Y: 읽음, N: 안읽음)
    CREATED_DATE DATE DEFAULT SYSDATE,                -- 생성일
    CONSTRAINT FK_BOARD_NOTIFICATION1_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER1(ID),
    CONSTRAINT FK_BOARD_NOTIFICATION1_POST FOREIGN KEY (RELATED_POST_SEQ) REFERENCES BOARD_POST1(POST_SEQ) ON DELETE CASCADE,
    CONSTRAINT FK_BOARD_NOTIFICATION1_COMMENT FOREIGN KEY (RELATED_COMMENT_SEQ) REFERENCES BOARD_COMMENT1(COMMENT_SEQ) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX IDX_BOARD_NOTIFICATION1_SEQ ON BOARD_NOTIFICATION1(NOTIFICATION_SEQ);
CREATE INDEX IDX_BOARD_NOTIFICATION1_MEMBER ON BOARD_NOTIFICATION1(MEMBER_ID);
CREATE INDEX IDX_BOARD_NOTIFICATION1_POST ON BOARD_NOTIFICATION1(RELATED_POST_SEQ);
CREATE INDEX IDX_BOARD_NOTIFICATION1_READ ON BOARD_NOTIFICATION1(MEMBER_ID, IS_READ);

-- 샘플 데이터 삽입 (선택사항)
-- INSERT INTO BOARD_NOTIFICATION1 (NOTIFICATION_SEQ, MEMBER_ID, NOTIFICATION_TYPE, RELATED_POST_SEQ, RELATED_COMMENT_SEQ, NOTIFICATION_CONTENT, IS_READ, CREATED_DATE)
-- VALUES (SEQ_BOARD_NOTIFICATION1.NEXTVAL, 'hong123', '게시글댓글', 1, 1, '새로운 댓글이 작성되었습니다.', 'N', SYSDATE);

COMMIT;

