-- MEMBER1 테이블에 계정 정지 관련 필드 추가
-- 기존 테이블에 컬럼을 추가하는 ALTER TABLE 문

-- 1. 계정 정지 여부 필드 추가 (Y: 정지, N: 정상, 기본값: N)
ALTER TABLE MEMBER1 ADD (
    IS_SUSPENDED VARCHAR2(1) DEFAULT 'N'
);

-- 2. 정지 시작일 필드 추가
ALTER TABLE MEMBER1 ADD (
    SUSPEND_START_DATE DATE
);

-- 3. 정지 종료일 필드 추가
ALTER TABLE MEMBER1 ADD (
    SUSPEND_END_DATE DATE
);

-- 4. 정지 사유 필드 추가
ALTER TABLE MEMBER1 ADD (
    SUSPEND_REASON VARCHAR2(500)
);

-- 5. 기존 데이터의 IS_SUSPENDED를 'N'으로 업데이트 (NULL인 경우)
UPDATE MEMBER1 SET IS_SUSPENDED = 'N' WHERE IS_SUSPENDED IS NULL;

-- 6. 인덱스 생성 (계정 정지 여부로 검색 시 성능 향상)
CREATE INDEX IDX_MEMBER1_SUSPENDED ON MEMBER1(IS_SUSPENDED);

-- 7. 확인 쿼리 (추가된 컬럼 확인)
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'MEMBER1'
ORDER BY COLUMN_ID;

